<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(AtomUITargetFrameworks)</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>GeneratedFiles</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/*.cs"/>
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets/**/*.*"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics"/>
        <PackageReference Include="AtomUI.Desktop.Controls"/>
        <PackageReference Include="AtomUI.Generator"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"
                          PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Debug'">
        <ProjectReference Include="../../src/AtomUI.Icons.Material/AtomUI.Icons.Material.csproj"/>
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Release'">
        <PackageReference Include="AtomUI.Icons.Material"/>
    </ItemGroup>
    
</Project>
