<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(AtomUITargetFrameworks)</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>GeneratedFiles</CompilerGeneratedFilesOutputPath>
        <AtomUILanguageContractVersion>2</AtomUILanguageContractVersion>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/*.cs"/>
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets/**/*.*"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="AvaloniaUI.DiagnosticsSupport"/>
        <PackageReference Include="AtomUI.Desktop.Controls"/>
        <PackageReference Include="AtomUI.Generator"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"
                          PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup Condition="'$(UsePublishedMaterialPackage)' != 'true' and '$(TargetFramework)' != ''">
        <ProjectReference Include="../../src/AtomUI.Icons.Material/AtomUI.Icons.Material.csproj"
                          SetTargetFramework="TargetFramework=$(TargetFramework)"/>
    </ItemGroup>

    <ItemGroup Condition="'$(UsePublishedMaterialPackage)' != 'true' and '$(TargetFramework)' == ''">
        <ProjectReference Include="../../src/AtomUI.Icons.Material/AtomUI.Icons.Material.csproj"/>
    </ItemGroup>

    <ItemGroup Condition="'$(UsePublishedMaterialPackage)' == 'true'">
        <PackageReference Include="AtomUI.Icons.Material"/>
    </ItemGroup>
    
</Project>
