<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(AtomUITargetFrameworks)</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>AtomUI.Icons.Material</RootNamespace>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="AtomUI.Core" />
    </ItemGroup>

</Project>
