// <auto-generated />
namespace AtomUI.Generated.MaterialGallery;

public static class IconGalleryThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "IconGallery");
}

public static class NavigationThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Navigation");
}

internal static class GeneratedControlThemeAssetManifest
{
    internal static global::System.Collections.Generic.IReadOnlyList<global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor> GetDescriptors()
    {
        return new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor[]
        {
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://MaterialGallery/IconGalleryTheme.axaml"), IconGalleryThemeAsset.Identity, 0xF2C700BE5131D897UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://MaterialGallery/IconInfoItemTheme.axaml"), IconGalleryThemeAsset.Identity, 0xF2C700BE5131D897UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://MaterialGallery/NavigationTheme.axaml"), NavigationThemeAsset.Identity, 0x83536C981B5F1BE5UL),
        };
    }
}
