// <auto-generated />
#nullable enable

[assembly: global::System.Reflection.AssemblyMetadata("AtomUILanguageModuleId", "MaterialGallery")]

namespace AtomUI.Generated.MaterialGallery
{
    internal static class GeneratedLanguageModuleRegistration
    {
        internal static void Register(global::AtomUI.Localization.ILocalizationBuilder builder)
        {
            global::System.ArgumentNullException.ThrowIfNull(builder);
            global::AtomUI.Generated.MaterialGallery.GeneratedLanguageCatalog_DE103DA7AF048651.Register(builder);
        }
    }
}
