// <auto-generated />
#nullable enable

namespace MaterialGallery.Localization
{
    public sealed class WorkspaceWindowLangResourceExtension
        : global::AtomUI.Localization.LanguageResourceExtension<global::MaterialGallery.Localization.WorkspaceWindowLangResourceKind>
    {
        public WorkspaceWindowLangResourceExtension()
        {
        }

        public WorkspaceWindowLangResourceExtension(
            global::MaterialGallery.Localization.WorkspaceWindowLangResourceKind kind)
            : base(kind)
        {
        }
    }
}
