// <auto-generated />
#nullable enable
namespace AtomUI.Generated.MaterialGallery;

internal static class GeneratedControlPackageRegistration
{
    internal static void Register(
        global::AtomUI.Theme.IThemeManagerBuilder themeManagerBuilder,
        global::AtomUI.Theme.Resources.IControlThemesProvider controlThemesProvider,
        global::System.Func<global::AtomUI.Theme.Schema.ControlTokenIdentity, bool>? includeIdentity = null,
        global::System.Func<global::System.Collections.Generic.IReadOnlyList<global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor>, global::System.Collections.Generic.IReadOnlyList<global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor>>? selectAssets = null)
    {
        global::System.ArgumentNullException.ThrowIfNull(themeManagerBuilder);
        global::System.ArgumentNullException.ThrowIfNull(controlThemesProvider);
        var controls = GeneratedThemeSchema.GetControls();
        var selectedControls = new global::System.Collections.Generic.List<global::AtomUI.Theme.Schema.ControlTokenDescriptor>(controls.Count);
        foreach (var control in controls)
        {
            if (includeIdentity is null || includeIdentity(control.Identity))
            {
                selectedControls.Add(control);
            }
        }

        var assets = GeneratedControlThemeAssetManifest.GetDescriptors();
        var selectedAssets = new global::System.Collections.Generic.List<global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor>(assets.Count);
        foreach (var asset in assets)
        {
            var includeAsset = includeIdentity is null || includeIdentity(asset.OwnerIdentity);
            if (includeAsset && includeIdentity is not null)
            {
                foreach (var referencedIdentity in asset.ReferencedControlIdentities)
                {
                    if (!includeIdentity(referencedIdentity))
                    {
                        includeAsset = false;
                        break;
                    }
                }
            }
            if (includeAsset)
            {
                selectedAssets.Add(asset);
            }
        }

        var packageAssets = selectAssets is null ? selectedAssets : selectAssets(selectedAssets);
        global::System.ArgumentNullException.ThrowIfNull(packageAssets);
        GeneratedControlThemeAssetResources.AddResources(controlThemesProvider, packageAssets);

        var package = new global::AtomUI.Theme.ControlPackageRegistration(
            controlThemesProvider.Id,
            selectedControls,
            packageAssets,
            controlThemesProvider);
        themeManagerBuilder.AddControlPackage(package);
    }
}
