// <auto-generated />
using global::AtomUI.Theme.Schema;

namespace AtomUI.Generated.MaterialGallery;

internal static class GeneratedThemeSchema
{
    private static readonly TokenDescriptor[] s_globalTokens = new TokenDescriptor[]
    {
    };

    private static readonly ControlTokenDescriptor[] s_controls = new ControlTokenDescriptor[]
    {
        new ControlTokenDescriptor(
            typeof(global::MaterialGallery.Controls.IconGallery),
            new ControlTokenIdentity("MaterialGallery", "IconGallery"),
            new TokenDescriptor[]
            {
                new TokenDescriptor("GalleryIconSize", 0, TokenStage.Control, typeof(global::System.Double), global::MaterialGallery.Controls.DesignTokens.IconGalleryTokenKind.GalleryIconSize,
                    static value => ThemeTokenValueParser.Parse<global::System.Double>(value),
                    static value => ThemeTokenValueFormatter.Format((global::System.Double)value!),
                    static token => ((global::MaterialGallery.Controls.IconGalleryToken)token).GalleryIconSize,
                    static (token, value) => ((global::MaterialGallery.Controls.IconGalleryToken)token).GalleryIconSize = (global::System.Double)value!,
                    static token => ThemeResourceValue.Project(((global::MaterialGallery.Controls.IconGalleryToken)token).GalleryIconSize)),
                new TokenDescriptor("InfoItemSize", 1, TokenStage.Control, typeof(global::System.Double), global::MaterialGallery.Controls.DesignTokens.IconGalleryTokenKind.InfoItemSize,
                    static value => ThemeTokenValueParser.Parse<global::System.Double>(value),
                    static value => ThemeTokenValueFormatter.Format((global::System.Double)value!),
                    static token => ((global::MaterialGallery.Controls.IconGalleryToken)token).InfoItemSize,
                    static (token, value) => ((global::MaterialGallery.Controls.IconGalleryToken)token).InfoItemSize = (global::System.Double)value!,
                    static token => ThemeResourceValue.Project(((global::MaterialGallery.Controls.IconGalleryToken)token).InfoItemSize)),
                new TokenDescriptor("SearchInputMargin", 2, TokenStage.Control, typeof(global::Avalonia.Thickness), global::MaterialGallery.Controls.DesignTokens.IconGalleryTokenKind.SearchInputMargin,
                    static value => ThemeTokenValueParser.Parse<global::Avalonia.Thickness>(value),
                    static value => ThemeTokenValueFormatter.Format((global::Avalonia.Thickness)value!),
                    static token => ((global::MaterialGallery.Controls.IconGalleryToken)token).SearchInputMargin,
                    static (token, value) => ((global::MaterialGallery.Controls.IconGalleryToken)token).SearchInputMargin = (global::Avalonia.Thickness)value!,
                    static token => ThemeResourceValue.Project(((global::MaterialGallery.Controls.IconGalleryToken)token).SearchInputMargin)),
            },
            static () => new global::MaterialGallery.Controls.IconGalleryToken(),
            static (token, appearance) => ((global::MaterialGallery.Controls.IconGalleryToken)token).CalculateTokenValues(appearance == global::AtomUI.Theme.ThemeAppearance.Dark)),
        new ControlTokenDescriptor(
            typeof(global::MaterialGallery.Controls.IconInfoItem),
            new ControlTokenIdentity("MaterialGallery", "IconInfoItem")
        ),
        new ControlTokenDescriptor(
            typeof(global::MaterialGallery.Controls.Navigation),
            new ControlTokenIdentity("MaterialGallery", "Navigation"),
            new TokenDescriptor[]
            {
                new TokenDescriptor("PanelWidth", 0, TokenStage.Control, typeof(global::System.Double), global::MaterialGallery.Controls.DesignTokens.NavigationTokenKind.PanelWidth,
                    static value => ThemeTokenValueParser.Parse<global::System.Double>(value),
                    static value => ThemeTokenValueFormatter.Format((global::System.Double)value!),
                    static token => ((global::MaterialGallery.Controls.NavigationToken)token).PanelWidth,
                    static (token, value) => ((global::MaterialGallery.Controls.NavigationToken)token).PanelWidth = (global::System.Double)value!,
                    static token => ThemeResourceValue.Project(((global::MaterialGallery.Controls.NavigationToken)token).PanelWidth)),
            },
            static () => new global::MaterialGallery.Controls.NavigationToken(),
            static (token, appearance) => ((global::MaterialGallery.Controls.NavigationToken)token).CalculateTokenValues(appearance == global::AtomUI.Theme.ThemeAppearance.Dark)),
    };

    private static readonly ThemeAlgorithmDescriptor[] s_algorithms = new ThemeAlgorithmDescriptor[]
    {
    };

    internal static global::System.Collections.Generic.IReadOnlyList<TokenDescriptor> GetGlobalTokens() => s_globalTokens;
    internal static global::System.Collections.Generic.IReadOnlyList<ControlTokenDescriptor> GetControls() => s_controls;
    internal static global::System.Collections.Generic.IReadOnlyList<ThemeAlgorithmDescriptor> GetAlgorithms() => s_algorithms;
}
